### ISSUE TITLE
Failed to load the atom-json-color package

### ISSUE THREAD

**Issue by vish-sn** [th00ber/atom-json-color#6]
Just upgraded the atom-json-color package and restarted atom and got below error.

**Atom**: 1.15.0 ia32
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [atom-json-color](https://github.com/th00ber/atom-json-color) package 0.6.0

### Stack Trace

Failed to load the atom-json-color package

```
At variable @default is undefined in C:\Users\vpatel\.atom\packages\atom-json-color\styles\json-colorer.less:5:15

LessError: variable @default is undefined
  at /packages/atom-json-color/styles/json-colorer.less:5:15
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.29.17 
atom-json-color 0.6.0 
atom-save-all 0.4.1 
busy-signal 1.3.0 
clipboard-plus 0.5.1 
cssfmt 1.4.0 
git-time-machine 1.5.6 
Handlebars 1.7.1 
highlight-selected 0.13.1 
intentions 1.1.2 
last-cursor-position 0.9.2 
linter 2.1.2 
linter-eslint 8.1.4 
linter-handlebars 2.3.4 
linter-ui-default 1.2.1 
pigments 0.39.1 
```

**Comment by th00ber** [comment]
It's weird. Did you still got the problem ?

**Comment by vish-sn** [comment]
That was gone later.

**Comment by rafaeelaudibert** [comment]
Same error to me today. Didn't updated the package or anything. Only ocurred once.

**Comment by huthief** [comment]
me too. Error alert always

**Comment by alsanchez-dev** [comment]
I just got this error alert!
